## CircleCI Config with Docker Images

version: 2
jobs:
  # Name of the job
  build:
    docker:
      #- image:  # Primary container
      - image: vitr/casperjs
        environment:
          IMG_TAG: example #$CIRCLE_PROJECT_REPONAME
      - image: waisbrot/wait
    steps:
      ## Steps of the job
      - checkout
      - run:
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i 's/{CLIENT_ID}/$AUTH0_TEST_CLIENT_ID/g' $AUTH0_CFG
            sed -i 's/{DOMAIN}/$AUTH0_TEST_DOMAIN/g' $AUTH0_CFG
          environment:
            AUTH0_CFG: 01-Login/src/app/auth/auth0-variables.ts
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            wget -O /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build PR Docker image
          command: |
            docker build -t $IMG_TAG 01-Login/.
      - run:
          name: Run PR Docker image
          command: |
            docker run -d --name $IMG_TAG -p 3000:3000 $IMG_TAG
      - run:
          name: Wait for app to be available
          command: |
            docker run --link $IMG_TAG:$IMG_TAG waisbrot/wait
      - run:
          name: Run CasperJS tests
          command: |
            wget -O tests.js https://gist.githubusercontent.com/lbalmaceda/3cef267b6bed563d5009a1ca851bac87/raw/ca629d7aa6cdd68b52e87b3cfa3f7f7a809dd297/webapp-test.js
            casperjs test tests.js --fail-fast --initial-url=http://localhost:3000 --xunit=/junit/test-results.xml
      - store_test_results:
          path: /junit
      - store_artifacts:
          path: ./screenshots
      - run:
          name: Stop PR Docker image
          command: |
            docker stop $(docker ps -q --filter ancestor=$IMG_TAG)